### ISSUE TITLE
NavBar layout

### ISSUE THREAD

**Issue by otamam818** [IshmamDC217/BUIT-ChobiGhor#1]
The current navbar on my desktop looks like this:  
![image](https://github.com/IshmamDC217/BUIT-Chobighor/assets/68072081/5948416c-7716-481f-a2f8-f2040c358405)

So far it looks great! I reckon that there should be a "Home" button on the left side (conventionally this being the logo of the Chobighor app). But given there is a  "Home" button already, I do want to discuss what your opinion is on ultimately removing this button and replacing it with a Logo on the left, since that is the convention.

Would it be too hard for our parents to infer that it is the home button? Then maybe we can replace it with a home icon?

Just telling you my opinions, let me know what you think.

EDIT: I made a prototype of my thoughts, based on what I feel like would be more familiar
![NavBar02](https://github.com/IshmamDC217/BUIT-Chobighor/assets/68072081/0024acef-a4ae-4a1e-937c-095db83ec150)

**Comment by IshmamDC217** [comment]
I really like that! Do you want to change it to that then? If so bear in mind that the mobile version looks like this:

![Screenshot 2023-06-18 082904](https://github.com/IshmamDC217/BUIT-Chobighor/assets/89687266/811460fb-87ef-44e1-8e00-e43b2e591bf2)

So you would have to change that as well

**Comment by IshmamDC217** [comment]
Also do you want a login system?

**Comment by otamam818** [comment]
A login system would make sense to our family (where there is no option to sign up) so that pictures of varying preferences can be added: personal, public, shared-personal (between family but not public)

It also depends on our parents' preference to the system when we have a MVP, but for now I would prefer working towards it

**Comment by IshmamDC217** [comment]
Cool. Yeah that would be perfect for mom and dad, especially since we want to upload some personal images. Then how about you handle log in today? I'll assign you that for today
