### ISSUE TITLE
Home Page has overlap

### ISSUE THREAD

**Issue by otamam818** [IshmamDC217/BUIT-ChobiGhor#7]
I tried it on my device and I got an overlap within the left-text and right-side cards:
![image](https://github.com/IshmamDC217/BUIT-ChobiGhor/assets/68072081/2a07bdfc-9f4d-4551-a454-8fbf2f6ad5e7)

Since I am working on this page, I am happy to look into it and fix it.

**Comment by IshmamDC217** [comment]
Yes please, but i think i know the issue. Is your display setting set to
100%? If it isnt then you shouldnt fix it and if it is then you should as
most users use 100%

**Comment by otamam818** [comment]
I checked at 100%. There is still an overlap, but I am hoping to fix it within my next push.

**Comment by IshmamDC217** [comment]
Okay nice one, it should just be adjusting the max width

**Comment by otamam818** [comment]
Problem has been fixed. I also tweaked the cards' aesthetic to look more consistent with the navigation bar
